from Segment import Segment

definitions = {
    "B1": Segment(tag="B1").structure(
        Segment(
            id="140",
            desc="Standard Carrier Alpha Code",
            DataType="None",
            Required=True,
            MinLength=2,
            MaxLength=4,
        ),
        Segment(
            id="145",
            desc="Shipment Identification Number",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=30,
        ),
        Segment(
            id="373",
            desc="Date",
            DataType="None",
            Required=False,
            MinLength=8,
            MaxLength=8,
        ),
        Segment(
            id="558",
            desc="Reservation Action Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="1073",
            desc="Yes/No Condition or Response Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="1658",
            desc="Shipment or Work Assignment Decline Reason Code",
            DataType="None",
            Required=False,
        ),
    ),
    "B2": Segment(tag="B2").structure(
        Segment(
            id="375",
            desc="Tariff Service Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="140",
            desc="Standard Carrier Alpha Code",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=4,
        ),
        Segment(
            id="154",
            desc="Standard Point Location Code",
            DataType="None",
            Required=False,
            MinLength=6,
            MaxLength=9,
        ),
        Segment(
            id="145",
            desc="Shipment Identification Number",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=30,
        ),
        Segment(
            id="188",
            desc="Weight Unit Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="146",
            desc="Shipment Method of Payment",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="147",
            desc="Shipment Qualifier",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="86",
            desc="Total Equipment",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=3,
        ),
        Segment(
            id="460",
            desc="Shipment Weight Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="501",
            desc="Customs Documentation Handling Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="335",
            desc="Transportation Terms Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="591",
            desc="Payment Method Code",
            DataType="None",
            Required=False,
        ),
    ),
    "B3": Segment(tag="B3").structure(
        Segment(
            id="147",
            desc="Shipment Qualifier",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="76",
            desc="Invoice Number",
            DataType="None",
            Required=True,
            MinLength=1,
            MaxLength=22,
        ),
        Segment(
            id="145",
            desc="Shipment Identification Number",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=30,
        ),
        Segment(
            id="146",
            desc="Shipment Method of Payment",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="188",
            desc="Weight Unit Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="373",
            desc="Date",
            DataType="None",
            Required=True,
            MinLength=8,
            MaxLength=8,
        ),
        Segment(
            id="193",
            desc="Net Amount Due",
            DataType="None",
            Required=True,
            MinLength=1,
            MaxLength=12,
        ),
        Segment(
            id="202",
            desc="Correction Indicator",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="32",
            desc="Delivery Date",
            DataType="None",
            Required=False,
            MinLength=8,
            MaxLength=8,
        ),
        Segment(
            id="374",
            desc="Date/Time Qualifier",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="140",
            desc="Standard Carrier Alpha Code",
            DataType="None",
            Required=True,
            MinLength=2,
            MaxLength=4,
        ),
        Segment(
            id="373",
            desc="Date",
            DataType="None",
            Required=False,
            MinLength=8,
            MaxLength=8,
        ),
        Segment(
            id="375",
            desc="Tariff Service Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="335",
            desc="Transportation Terms Code",
            DataType="None",
            Required=False,
        ),
    ),
    "B4": Segment(tag="B4").structure(
        Segment(
            id="152",
            desc="Special Handling Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="71",
            desc="Inquiry Request Number",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=3,
        ),
        Segment(
            id="157",
            desc="Shipment Status Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="373",
            desc="Date",
            DataType="None",
            Required=False,
            MinLength=8,
            MaxLength=8,
        ),
        Segment(
            id="337",
            desc="Time",
            DataType="None",
            Required=False,
            MinLength=4,
            MaxLength=8,
        ),
        Segment(
            id="159",
            desc="Status Location",
            DataType="None",
            Required=False,
            MinLength=3,
            MaxLength=5,
        ),
        Segment(
            id="206",
            desc="Equipment Initial",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=4,
        ),
        Segment(
            id="207",
            desc="Equipment Number",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=15,
        ),
        Segment(
            id="578",
            desc="Equipment Status Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="24",
            desc="Equipment Type",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="310",
            desc="Location Identifier",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=30,
        ),
        Segment(
            id="309",
            desc="Location Qualifier",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="761",
            desc="Equipment Number Check Digit",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=1,
        ),
    ),
    "B9": Segment(tag="B9").structure(
        Segment(
            id="127",
            desc="Reference Identification",
            DataType="None",
            Required=True,
            MinLength=1,
            MaxLength=50,
        ),
        Segment(
            id="353",
            desc="Transaction Set Purpose Code",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="146",
            desc="Shipment Method of Payment",
            DataType="None",
            Required=False,
        ),
    ),
    "BC": Segment(tag="BC").structure(
        Segment(
            id="353",
            desc="Transaction Set Purpose Code",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="373",
            desc="Date",
            DataType="None",
            Required=False,
            MinLength=8,
            MaxLength=8,
        ),
        Segment(
            id="337",
            desc="Time",
            DataType="None",
            Required=False,
            MinLength=4,
            MaxLength=8,
        ),
        Segment(
            id="127",
            desc="Reference Identification",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=50,
        ),
        Segment(
            id="127",
            desc="Reference Identification",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=50,
        ),
        Segment(
            id="640",
            desc="Transaction Type Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="306",
            desc="Action Code",
            DataType="None",
            Required=False,
        ),
    ),
    "BL": Segment(tag="BL").structure(
        Segment(
            id="747",
            desc="Rebill Reason Code",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="573",
            desc="Freight Station Accounting Code",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=5,
        ),
        Segment(
            id="573",
            desc="Freight Station Accounting Code",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=5,
        ),
        Segment(
            id="154",
            desc="Standard Point Location Code",
            DataType="None",
            Required=False,
            MinLength=6,
            MaxLength=9,
        ),
        Segment(
            id="19",
            desc="City Name",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=30,
        ),
        Segment(
            id="156",
            desc="State or Province Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="26",
            desc="Country Code",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=3,
        ),
        Segment(
            id="154",
            desc="Standard Point Location Code",
            DataType="None",
            Required=False,
            MinLength=6,
            MaxLength=9,
        ),
        Segment(
            id="19",
            desc="City Name",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=30,
        ),
        Segment(
            id="156",
            desc="State or Province Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="26",
            desc="Country Code",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=3,
        ),
        Segment(
            id="140",
            desc="Standard Carrier Alpha Code",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=4,
        ),
        Segment(
            id="140",
            desc="Standard Carrier Alpha Code",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=4,
        ),
        Segment(
            id="140",
            desc="Standard Carrier Alpha Code",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=4,
        ),
        Segment(
            id="140",
            desc="Standard Carrier Alpha Code",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=4,
        ),
        Segment(
            id="140",
            desc="Standard Carrier Alpha Code",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=4,
        ),
        Segment(
            id="140",
            desc="Standard Carrier Alpha Code",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=4,
        ),
    ),
    "BR": Segment(tag="BR").structure(
        Segment(
            id="353",
            desc="Transaction Set Purpose Code",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="640",
            desc="Transaction Type Code",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="373",
            desc="Date",
            DataType="None",
            Required=True,
            MinLength=8,
            MaxLength=8,
        ),
        Segment(
            id="67",
            desc="Identification Code",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=80,
        ),
        Segment(
            id="66",
            desc="Identification Code Qualifier",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="306",
            desc="Action Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="128",
            desc="Reference Identification Qualifier",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="127",
            desc="Reference Identification",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=50,
        ),
        Segment(
            id="337",
            desc="Time",
            DataType="None",
            Required=False,
            MinLength=4,
            MaxLength=8,
        ),
        Segment(
            id="128",
            desc="Reference Identification Qualifier",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="127",
            desc="Reference Identification",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=50,
        ),
    ),
    "BW": Segment(tag="BW").structure(
        Segment(
            id="298",
            desc="Origin EDI Carrier Code",
            DataType="None",
            Required=True,
            MinLength=2,
            MaxLength=4,
        ),
        Segment(
            id="145",
            desc="Shipment Identification Number",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=30,
        ),
        Segment(
            id="188",
            desc="Weight Unit Code",
            DataType="None",
            Required=True,
        ),
    ),
    "BX": Segment(tag="BX").structure(
        Segment(
            id="353",
            desc="Transaction Set Purpose Code",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="91",
            desc="Transportation Method/Type Code",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="146",
            desc="Shipment Method of Payment",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="145",
            desc="Shipment Identification Number",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=30,
        ),
        Segment(
            id="140",
            desc="Standard Carrier Alpha Code",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=4,
        ),
        Segment(
            id="188",
            desc="Weight Unit Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="147",
            desc="Shipment Qualifier",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="226",
            desc="Section Seven Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="195",
            desc="Capacity Load Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="160",
            desc="Status Report Request Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="501",
            desc="Customs Documentation Handling Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="199",
            desc="Confidential Billing Request Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="714",
            desc="Goods and Services Tax Reason Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="346",
            desc="Application Type",
            DataType="None",
            Required=False,
        ),
    ),
    "C2": Segment(tag="C2").structure(
        Segment(
            id="8",
            desc="Bank Client Code",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="66",
            desc="Identification Code Qualifier",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="67",
            desc="Identification Code",
            DataType="None",
            Required=True,
            MinLength=2,
            MaxLength=80,
        ),
        Segment(
            id="20",
            desc="Client Bank Number",
            DataType="None",
            Required=False,
            MinLength=3,
            MaxLength=9,
        ),
        Segment(
            id="7",
            desc="Bank Account Number",
            DataType="None",
            Required=False,
            MinLength=6,
            MaxLength=17,
        ),
        Segment(
            id="107",
            desc="Payment Method Type Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="373",
            desc="Date",
            DataType="None",
            Required=False,
            MinLength=8,
            MaxLength=8,
        ),
    ),
    "C3": Segment(tag="C3").structure(
        Segment(
            id="100",
            desc="Currency Code",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="280",
            desc="Exchange Rate",
            DataType="None",
            Required=False,
            MinLength=4,
            MaxLength=10,
        ),
        Segment(
            id="100",
            desc="Currency Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="100",
            desc="Currency Code",
            DataType="None",
            Required=False,
        ),
    ),
    "C4": Segment(tag="C4").structure(
        Segment(
            id="100",
            desc="Currency Code",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="193",
            desc="Net Amount Due",
            DataType="None",
            Required=True,
            MinLength=1,
            MaxLength=12,
        ),
    ),
    "C8": Segment(tag="C8").structure(
        Segment(
            id="213",
            desc="Lading Line Item Number",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=3,
        ),
        Segment(
            id="246",
            desc="Certification/Clause Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="247",
            desc="Certification/Clause Text",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=60,
        ),
        Segment(
            id="1302",
            desc="Shipper's Export Declaration Requirements",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=2,
        ),
    ),
    "CD": Segment(tag="CD").structure(
        Segment(
            id="495",
            desc="Condition Segment Logical Connector",
            DataType="None",
            Required=True,
            MinLength=1,
            MaxLength=3,
        ),
        Segment(
            id="498",
            desc="Condition Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="499",
            desc="Condition Value",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=10,
        ),
        Segment(
            id="499",
            desc="Condition Value",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=10,
        ),
        Segment(
            id="499",
            desc="Condition Value",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=10,
        ),
        Segment(
            id="554",
            desc="Assigned Number",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=6,
        ),
        Segment(
            id="259",
            desc="Change Type Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="140",
            desc="Standard Carrier Alpha Code",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=4,
        ),
        Segment(
            id="697",
            desc="Docket Control Number",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=7,
        ),
        Segment(
            id="690",
            desc="Docket Identification",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=11,
        ),
        Segment(
            id="260",
            desc="Group Title",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=30,
        ),
    ),
    "CI": Segment(tag="CI").structure(
        Segment(
            id="93",
            desc="Name",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=60,
        ),
        Segment(
            id="140",
            desc="Standard Carrier Alpha Code",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=4,
        ),
        Segment(
            id="66",
            desc="Identification Code Qualifier",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="67",
            desc="Identification Code",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=80,
        ),
        Segment(
            id="66",
            desc="Identification Code Qualifier",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="67",
            desc="Identification Code",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=80,
        ),
        Segment(
            id="772",
            desc="Interchange Agreement Status Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="374",
            desc="Date/Time Qualifier",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="373",
            desc="Date",
            DataType="None",
            Required=False,
            MinLength=8,
            MaxLength=8,
        ),
        Segment(
            id="374",
            desc="Date/Time Qualifier",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="373",
            desc="Date",
            DataType="None",
            Required=False,
            MinLength=8,
            MaxLength=8,
        ),
        Segment(
            id="93",
            desc="Name",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=60,
        ),
        Segment(
            id="128",
            desc="Reference Identification Qualifier",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="127",
            desc="Reference Identification",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=50,
        ),
    ),
    "CM": Segment(tag="CM").structure(
        Segment(
            id="55",
            desc="Flight/Voyage Number",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=10,
        ),
        Segment(
            id="115",
            desc="Port or Terminal Function Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="114",
            desc="Port Name",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=24,
        ),
        Segment(
            id="373",
            desc="Date",
            DataType="None",
            Required=False,
            MinLength=8,
            MaxLength=8,
        ),
        Segment(
            id="13",
            desc="Booking Number",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=17,
        ),
        Segment(
            id="140",
            desc="Standard Carrier Alpha Code",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=4,
        ),
        Segment(
            id="140",
            desc="Standard Carrier Alpha Code",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=4,
        ),
        Segment(
            id="373",
            desc="Date",
            DataType="None",
            Required=False,
            MinLength=8,
            MaxLength=8,
        ),
        Segment(
            id="182",
            desc="Vessel Name",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=28,
        ),
        Segment(
            id="113",
            desc="Pier Number",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=4,
        ),
        Segment(
            id="112",
            desc="Pier Name",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=14,
        ),
        Segment(
            id="174",
            desc="Terminal Name",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=30,
        ),
        Segment(
            id="156",
            desc="State or Province Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="26",
            desc="Country Code",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=3,
        ),
        Segment(
            id="127",
            desc="Reference Identification",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=50,
        ),
        Segment(
            id="202",
            desc="Correction Indicator",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="91",
            desc="Transportation Method/Type Code",
            DataType="None",
            Required=False,
        ),
    ),
    "CQ": Segment(tag="CQ").structure(
        Segment(
            id="1729",
            desc="Credential Type Code",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="1731",
            desc="Credential Category Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="66",
            desc="Identification Code Qualifier",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="67",
            desc="Identification Code",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=80,
        ),
        Segment(
            id="1131",
            desc="Level of Individual, Test, or Course Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="1147",
            desc="Basis for Academic Credit or Award of Credential Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="1730",
            desc="Credential Requirement Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="1073",
            desc="Yes/No Condition or Response Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="1321",
            desc="Condition Indicator",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="156",
            desc="State or Province Code",
            DataType="None",
            Required=False,
        ),
    ),
    "CS": Segment(tag="CS").structure(
        Segment(
            id="367",
            desc="Contract Number",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=30,
        ),
        Segment(
            id="327",
            desc="Change Order Sequence Number",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=8,
        ),
        Segment(
            id="328",
            desc="Release Number",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=30,
        ),
        Segment(
            id="128",
            desc="Reference Identification Qualifier",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="127",
            desc="Reference Identification",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=50,
        ),
        Segment(
            id="324",
            desc="Purchase Order Number",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=22,
        ),
        Segment(
            id="560",
            desc="Special Services Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="433",
            desc="F.O.B. Point Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="954",
            desc="Percentage as Decimal",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=10,
        ),
        Segment(
            id="954",
            desc="Percentage as Decimal",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=10,
        ),
        Segment(
            id="782",
            desc="Monetary Amount",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=18,
        ),
        Segment(
            id="336",
            desc="Terms Type Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="560",
            desc="Special Services Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="355",
            desc="Unit or Basis for Measurement Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="212",
            desc="Unit Price",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=17,
        ),
        Segment(
            id="336",
            desc="Terms Type Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="1073",
            desc="Yes/No Condition or Response Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="1073",
            desc="Yes/No Condition or Response Code",
            DataType="None",
            Required=False,
        ),
    ),
    "CT": Segment(tag="CT").structure(
        Segment(
            id="1073",
            desc="Yes/No Condition or Response Code",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="301",
            desc="Car Type Code",
            DataType="None",
            Required=True,
            MinLength=1,
            MaxLength=4,
        ),
        Segment(
            id="301",
            desc="Car Type Code",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=4,
        ),
    ),
    "CV": Segment(tag="CV").structure(
        Segment(
            id="322",
            desc="Load/Empty Status Code",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="482",
            desc="Payment Action Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="1014",
            desc="Car Type Group Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="519",
            desc="Time Period Unit Qualifier",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="380",
            desc="Quantity",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=15,
        ),
        Segment(
            id="1015",
            desc="Mileage Settlement Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="380",
            desc="Quantity",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=15,
        ),
        Segment(
            id="380",
            desc="Quantity",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=15,
        ),
        Segment(
            id="782",
            desc="Monetary Amount",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=18,
        ),
        Segment(
            id="782",
            desc="Monetary Amount",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=18,
        ),
        Segment(
            id="782",
            desc="Monetary Amount",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=18,
        ),
        Segment(
            id="782",
            desc="Monetary Amount",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=18,
        ),
        Segment(
            id="782",
            desc="Monetary Amount",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=18,
        ),
        Segment(
            id="1016",
            desc="Penalty Code",
            DataType="None",
            Required=False,
        ),
    ),
    "D9": Segment(tag="D9").structure(
        Segment(
            id="573",
            desc="Freight Station Accounting Code",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=5,
        ),
        Segment(
            id="19",
            desc="City Name",
            DataType="None",
            Required=True,
            MinLength=2,
            MaxLength=30,
        ),
        Segment(
            id="156",
            desc="State or Province Code",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="26",
            desc="Country Code",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=3,
        ),
        Segment(
            id="573",
            desc="Freight Station Accounting Code",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=5,
        ),
        Segment(
            id="19",
            desc="City Name",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=30,
        ),
        Segment(
            id="156",
            desc="State or Province Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="154",
            desc="Standard Point Location Code",
            DataType="None",
            Required=False,
            MinLength=6,
            MaxLength=9,
        ),
        Segment(
            id="116",
            desc="Postal Code",
            DataType="None",
            Required=False,
            MinLength=3,
            MaxLength=15,
        ),
        Segment(
            id="154",
            desc="Standard Point Location Code",
            DataType="None",
            Required=False,
            MinLength=6,
            MaxLength=9,
        ),
        Segment(
            id="116",
            desc="Postal Code",
            DataType="None",
            Required=False,
            MinLength=3,
            MaxLength=15,
        ),
        Segment(
            id="26",
            desc="Country Code",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=3,
        ),
    ),
    "DB": Segment(tag="DB").structure(
        Segment(
            id="1250",
            desc="Date Time Period Format Qualifier",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="1251",
            desc="Date Time Period",
            DataType="None",
            Required=True,
            MinLength=1,
            MaxLength=35,
        ),
        Segment(
            id="782",
            desc="Monetary Amount",
            DataType="None",
            Required=True,
            MinLength=1,
            MaxLength=18,
        ),
        Segment(
            id="782",
            desc="Monetary Amount",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=18,
        ),
        Segment(
            id="782",
            desc="Monetary Amount",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=18,
        ),
        Segment(
            id="1073",
            desc="Yes/No Condition or Response Code",
            DataType="None",
            Required=False,
        ),
    ),
    "DD": Segment(tag="DD").structure(
        Segment(
            id="1271",
            desc="Industry Code",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=30,
        ),
        Segment(
            id="1270",
            desc="Code List Qualifier Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="128",
            desc="Reference Identification Qualifier",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="127",
            desc="Reference Identification",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=50,
        ),
        Segment(
            id="1271",
            desc="Industry Code",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=30,
        ),
        Segment(
            id="1270",
            desc="Code List Qualifier Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="380",
            desc="Quantity",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=15,
        ),
        Segment(
            id="1073",
            desc="Yes/No Condition or Response Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="1271",
            desc="Industry Code",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=30,
        ),
        Segment(
            id="1270",
            desc="Code List Qualifier Code",
            DataType="None",
            Required=False,
        ),
    ),
    "DH": Segment(tag="DH").structure(
        Segment(
            id="678",
            desc="Ship/Delivery or Calendar Pattern Code",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="337",
            desc="Time",
            DataType="None",
            Required=True,
            MinLength=4,
            MaxLength=8,
        ),
        Segment(
            id="337",
            desc="Time",
            DataType="None",
            Required=True,
            MinLength=4,
            MaxLength=8,
        ),
    ),
    "DK": Segment(tag="DK").structure(
        Segment(
            id="140",
            desc="Standard Carrier Alpha Code",
            DataType="None",
            Required=True,
            MinLength=2,
            MaxLength=4,
        ),
        Segment(
            id="697",
            desc="Docket Control Number",
            DataType="None",
            Required=True,
            MinLength=1,
            MaxLength=7,
        ),
        Segment(
            id="690",
            desc="Docket Identification",
            DataType="None",
            Required=True,
            MinLength=1,
            MaxLength=11,
        ),
        Segment(
            id="691",
            desc="Revision Number",
            DataType="None",
            Required=True,
            MinLength=1,
            MaxLength=4,
        ),
        Segment(
            id="692",
            desc="Conveyance Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="693",
            desc="Docket Type Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="373",
            desc="Date",
            DataType="None",
            Required=False,
            MinLength=8,
            MaxLength=8,
        ),
        Segment(
            id="373",
            desc="Date",
            DataType="None",
            Required=False,
            MinLength=8,
            MaxLength=8,
        ),
        Segment(
            id="346",
            desc="Application Type",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="260",
            desc="Group Title",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=30,
        ),
    ),
    "DL": Segment(tag="DL").structure(
        Segment(
            id="306",
            desc="Action Code",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="542",
            desc="Labor Hours",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=3,
        ),
        Segment(
            id="542",
            desc="Labor Hours",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=3,
        ),
        Segment(
            id="1073",
            desc="Yes/No Condition or Response Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="610",
            desc="Amount",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=15,
        ),
        Segment(
            id="1470",
            desc="Number",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=9,
        ),
        Segment(
            id="1470",
            desc="Number",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=9,
        ),
        Segment(
            id="1073",
            desc="Yes/No Condition or Response Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="1073",
            desc="Yes/No Condition or Response Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="1073",
            desc="Yes/No Condition or Response Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="1073",
            desc="Yes/No Condition or Response Code",
            DataType="None",
            Required=False,
        ),
    ),
    "DM": Segment(tag="DM").structure(
        Segment(
            id="262",
            desc="Geography Qualifier Code",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="122",
            desc="Rate/Value Qualifier",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="176",
            desc="Time Qualifier",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="337",
            desc="Time",
            DataType="None",
            Required=False,
            MinLength=4,
            MaxLength=8,
        ),
        Segment(
            id="616",
            desc="Number of Periods",
            DataType="None",
            Required=True,
            MinLength=1,
            MaxLength=3,
        ),
        Segment(
            id="615",
            desc="Time Period Qualifier",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="616",
            desc="Number of Periods",
            DataType="None",
            Required=True,
            MinLength=1,
            MaxLength=3,
        ),
        Segment(
            id="118",
            desc="Rate",
            DataType="None",
            Required=True,
            MinLength=1,
            MaxLength=9,
        ),
        Segment(
            id="177",
            desc="Intermodal Service Code",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=2,
        ),
        Segment(
            id="257",
            desc="Tariff Application Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="11",
            desc="Billing Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="615",
            desc="Time Period Qualifier",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="616",
            desc="Number of Periods",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=3,
        ),
        Segment(
            id="616",
            desc="Number of Periods",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=3,
        ),
        Segment(
            id="118",
            desc="Rate",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=9,
        ),
        Segment(
            id="616",
            desc="Number of Periods",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=3,
        ),
        Segment(
            id="118",
            desc="Rate",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=9,
        ),
        Segment(
            id="616",
            desc="Number of Periods",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=3,
        ),
        Segment(
            id="118",
            desc="Rate",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=9,
        ),
        Segment(
            id="616",
            desc="Number of Periods",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=3,
        ),
        Segment(
            id="118",
            desc="Rate",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=9,
        ),
    ),
    "DN": Segment(tag="DN").structure(
        Segment(
            id="432",
            desc="Date Qualifier",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="373",
            desc="Date",
            DataType="None",
            Required=True,
            MinLength=8,
            MaxLength=8,
        ),
        Segment(
            id="1242",
            desc="Demand Area",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="1243",
            desc="Financial Status",
            DataType="None",
            Required=False,
        ),
    ),
    "DP": Segment(tag="DP").structure(
        Segment(
            id="306",
            desc="Action Code",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="234",
            desc="Product/Service ID",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=48,
        ),
        Segment(
            id="610",
            desc="Amount",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=15,
        ),
        Segment(
            id="610",
            desc="Amount",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=15,
        ),
        Segment(
            id="1073",
            desc="Yes/No Condition or Response Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="1321",
            desc="Condition Indicator",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="1073",
            desc="Yes/No Condition or Response Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="1073",
            desc="Yes/No Condition or Response Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="1073",
            desc="Yes/No Condition or Response Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="1073",
            desc="Yes/No Condition or Response Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="380",
            desc="Quantity",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=15,
        ),
        Segment(
            id="234",
            desc="Product/Service ID",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=48,
        ),
        Segment(
            id="369",
            desc="Free-form Description",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=45,
        ),
        Segment(
            id="332",
            desc="Percent, Decimal Format",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=6,
        ),
        Segment(
            id="360",
            desc="Allowance or Charge Total Amount",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=15,
        ),
        Segment(
            id="1073",
            desc="Yes/No Condition or Response Code",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="1073",
            desc="Yes/No Condition or Response Code",
            DataType="None",
            Required=False,
        ),
    ),
    "DR": Segment(tag="DR").structure(
        Segment(
            id="373",
            desc="Date",
            DataType="None",
            Required=True,
            MinLength=8,
            MaxLength=8,
        ),
        Segment(
            id="140",
            desc="Standard Carrier Alpha Code",
            DataType="None",
            Required=True,
            MinLength=2,
            MaxLength=4,
        ),
        Segment(
            id="697",
            desc="Docket Control Number",
            DataType="None",
            Required=True,
            MinLength=1,
            MaxLength=7,
        ),
        Segment(
            id="690",
            desc="Docket Identification",
            DataType="None",
            Required=True,
            MinLength=1,
            MaxLength=11,
        ),
        Segment(
            id="691",
            desc="Revision Number",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=4,
        ),
        Segment(
            id="690",
            desc="Docket Identification",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=11,
        ),
    ),
    "E1": Segment(tag="E1").structure(
        Segment(
            id="93",
            desc="Name",
            DataType="None",
            Required=True,
            MinLength=1,
            MaxLength=60,
        ),
        Segment(
            id="66",
            desc="Identification Code Qualifier",
            DataType="None",
            Required=False,
        ),
        Segment(
            id="67",
            desc="Identification Code",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=80,
        ),
    ),
    "E4": Segment(tag="E4").structure(
        Segment(
            id="19",
            desc="City Name",
            DataType="None",
            Required=True,
            MinLength=2,
            MaxLength=30,
        ),
        Segment(
            id="156",
            desc="State or Province Code",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="116",
            desc="Postal Code",
            DataType="None",
            Required=False,
            MinLength=3,
            MaxLength=15,
        ),
        Segment(
            id="26",
            desc="Country Code",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=3,
        ),
    ),
    "E5": Segment(tag="E5").structure(
        Segment(
            id="140",
            desc="Standard Carrier Alpha Code",
            DataType="None",
            Required=True,
            MinLength=2,
            MaxLength=4,
        ),
        Segment(
            id="133",
            desc="Routing Sequence Code",
            DataType="None",
            Required=True,
        ),
        Segment(
            id="19",
            desc="City Name",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=30,
        ),
        Segment(
            id="154",
            desc="Standard Point Location Code",
            DataType="None",
            Required=False,
            MinLength=6,
            MaxLength=9,
        ),
    ),
    "E6": Segment(tag="E6").structure(
        Segment(
            id="206",
            desc="Equipment Initial",
            DataType="None",
            Required=True,
            MinLength=1,
            MaxLength=4,
        ),
        Segment(
            id="207",
            desc="Equipment Number",
            DataType="None",
            Required=True,
            MinLength=1,
            MaxLength=15,
        ),
        Segment(
            id="19",
            desc="City Name",
            DataType="None",
            Required=True,
            MinLength=2,
            MaxLength=30,
        ),
        Segment(
            id="154",
            desc="Standard Point Location Code",
            DataType="None",
            Required=False,
            MinLength=6,
            MaxLength=9,
        ),
        Segment(
            id="140",
            desc="Standard Carrier Alpha Code",
            DataType="None",
            Required=True,
            MinLength=2,
            MaxLength=4,
        ),
        Segment(
            id="296",
            desc="Intermediate Switch Carrier",
            DataType="None",
            Required=False,
            MinLength=2,
            MaxLength=4,
        ),
        Segment(
            id="22",
            desc="Commodity Code",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=30,
        ),
        Segment(
            id="301",
            desc="Car Type Code",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=4,
        ),
        Segment(
            id="578",
            desc="Equipment Status Code",
            DataType="None",
            Required=True,
        ),
    ),
    "E8": Segment(tag="E8").structure(
        Segment(
            id="42",
            desc="Block Identifier",
            DataType="None",
            Required=False,
            MinLength=1,
            MaxLength=12,
        ),
        Segment(
            id="748",
            desc="Movement Authority Code",
            DataType="None",
            Required=False,
        ),
    ),
}
